// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: pkg/protocol/protocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommandMessage represents a command to be executed on the server
type CommandMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol version
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// HMAC signature for authentication (hex-encoded string)
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// Tool name to execute (e.g., "ffmpeg", "ffprobe")
	ToolName string `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Command line arguments
	Arguments     []string `protobuf:"bytes,4,rep,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandMessage) Reset() {
	*x = CommandMessage{}
	mi := &file_pkg_protocol_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandMessage) ProtoMessage() {}

func (x *CommandMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandMessage.ProtoReflect.Descriptor instead.
func (*CommandMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *CommandMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CommandMessage) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *CommandMessage) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *CommandMessage) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

var File_pkg_protocol_protocol_proto protoreflect.FileDescriptor

const file_pkg_protocol_protocol_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/protocol/protocol.proto\x12\bprotocol\"\x83\x01\n" +
	"\x0eCommandMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x1c\n" +
	"\targuments\x18\x04 \x03(\tR\targumentsB3Z1github.com/steelbrain/ffmpeg-over-ip/pkg/protocolb\x06proto3"

var (
	file_pkg_protocol_protocol_proto_rawDescOnce sync.Once
	file_pkg_protocol_protocol_proto_rawDescData []byte
)

func file_pkg_protocol_protocol_proto_rawDescGZIP() []byte {
	file_pkg_protocol_protocol_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_protocol_proto_rawDesc), len(file_pkg_protocol_protocol_proto_rawDesc)))
	})
	return file_pkg_protocol_protocol_proto_rawDescData
}

var file_pkg_protocol_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_protocol_protocol_proto_goTypes = []any{
	(*CommandMessage)(nil), // 0: protocol.CommandMessage
}
var file_pkg_protocol_protocol_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_protocol_protocol_proto_init() }
func file_pkg_protocol_protocol_proto_init() {
	if File_pkg_protocol_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_protocol_proto_rawDesc), len(file_pkg_protocol_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_protocol_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_protocol_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_protocol_proto_msgTypes,
	}.Build()
	File_pkg_protocol_protocol_proto = out.File
	file_pkg_protocol_protocol_proto_goTypes = nil
	file_pkg_protocol_protocol_proto_depIdxs = nil
}
